

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'A space saga of epic proportions where choices matter.', 'The Mass Effect Trilogy follows Commander Shepard on a quest to save the galaxy from the Reapers ancient machines bent on annihilating all sentient life. Players experience immersive storytelling deep relationships and thrilling combat. Choices impact the fate of the galaxy.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'An epic story of survival set in Americas unforgiving heartland.', 'Step into the shoes of outlaw Arthur Morgan as he grapples with the waning age of the Wild West. In an open world full of rich stories and breathtaking visuals players navigate moral choices and loyalty. This immersive world is filled with life danger and consequence.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'Hunt monsters and uncover secrets in a vast dark fantasy world.', 'Playing as Geralt of Rivia a monster hunter players explore a vast open world filled with rich lore challenging battles and complex moral decisions. The story centers around Geralts search for his adopted daughter set against the backdrop of a war-torn land and a supernatural threat.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Venture into feudal Japan as a lone skilled shinobi.', 'In Sekiro players take on the role of a shinobi seeking revenge in a twisted mythological Japan. With punishing combat and unique stealth mechanics players must use tactics and timing to overcome powerful foes while unraveling the mysteries of immortality.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Become a samurai in the midst of the Mongol invasion of Japan.', 'Players follow the journey of Jin Sakai a samurai warrior who must adopt unconventional tactics to repel Mongol invaders. Set in a stunning open world players explore feudal Japan honor the code of the samurai and engage in beautifully crafted combat. ');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Classic adventure in the Mushroom Kingdom.', 'Join Mario as he traverses Dinosaur Land to rescue Princess Toadstool from the evil Bowser. This classic platformer offers a variety of levels power-ups and secrets to discover making it one of the most beloved entries in the Mario series.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'A haunting journey through the ruined kingdom of Hallownest.', 'Players explore a dark mysterious world filled with challenging enemies intriguing lore and beautifully crafted environments. As a nameless knight they unravel the secrets of Hallownest face daunting bosses and acquire new abilities in this metroidvania adventure.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'A touching story of courage in a beautifully crafted world.', 'Follow Ori a guardian spirit as they journey through a mystical forest to save it from a dark force. This game combines challenging platforming with a heartfelt story stunning visuals and a hauntingly beautiful soundtrack.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'A run-and-gun game inspired by 1930s cartoons.', 'In Cuphead players face a series of boss battles in a world drawn in the style of 1930s cartoons. Known for its high difficulty and unique aesthetic the game follows Cuphead and Mugman as they attempt to repay a debt to the devil.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Speed through time to save Little Planet from Dr. Robotnik.', 'Sonic races through levels in both the past present and future to stop Dr. Robotnik from taking over Little Planet. Featuring iconic music and fast-paced platforming this game remains a classic in the Sonic series.');

